needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  # CVAE params
  kernel_size: 3
  radius: 1
  connectivity: 8
  encoder_pool: max
  lr_cvae: 1e-3
  weight_decay_cvae: 1e-4
  beta_max: 1e-1
  beta_epoch_max: 5
  epochs_cvae: 30
  encoder_conv1: 64
  encoder_conv2: 2
  # temporal unet head (matched to temporal_unet.yaml)
  head: temporal_unet
  epochs_head: 50
  lr_head: 1e-3
  weight_decay_head: 1e-4
  bilinear: true
  unet_base_chan: 32


tune:
  param_space:
    # CVAE tuning
    weight_decay_cvae:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1e-3]
    lr_cvae:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-2]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-3, 1]
    # UNet head tuning (same ranges as temporal_unet.yaml)
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]
    lr_head:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-2]
    weight_decay_head:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1e-3]
