logdir: benchmarks/results

# make sure it is also compatible with the cluster.yaml
# and the config file at benchmarks/run/config.yaml
concurrency: 30
mem_mb: 4000
cpus_per_task: 80
overwrite: false

spaceenvs:
  cont:
    - 
  disc:
    # - healthdgraph_rad1_pollutn_mortality_disc
    # - healthdgraph_rad2_pollutn_mortality_disc
    
    # - small_healthdgrid_rad1_pollutn_mortality_disc
    
    # - healthdgrid_rad1_pollutn_mortality_disc
    # - healthdgrid_rad2_pollutn_mortality_disc
    
    - pm25grid_rad1_so4_pm_disc
    # - pm25grid_rad2_so4_pm_disc


algorithms:
  cont:
    # - spatial
    # - spatialplus
    # - xgboost
    # - ols
    # - gcn
    # - s2sls-lag1
    # - s2sls-lag2
    # - gmerror
    # - deconfounder
  disc:
    # - dapsm
    # - spatial
    # - spatialplus
    # - gcn
    # - s2sls-lag1
    - deconfounder_r0
    # - deconfounder_r1
    # - deconfounder_r2

