logdir: benchmarks/results

# make sure it is also compatible with the cluster.yaml
# and the config file at benchmarks/run/config.yaml
concurrency: 64
mem_mb: 400000
cpus_per_task: 4
overwrite: true

spaceenvs:
  cont:
    - 
  disc:    
    # - nonlocal_small_healthdgrid_rad1_pollutn_mortality_disc
    # - nonlocal_small_healthdgrid_rad2_pollutn_mortality_disc
    
    - small_healthdgrid_rad1_pollutn_mortality_disc
    - small_healthdgrid_rad2_pollutn_mortality_disc
    
    # - nonlocal_pm25grid_rad1_so4_pm_disc
    # - nonlocal_pm25grid_rad2_so4_pm_disc
    
    # - pm25grid_rad1_so4_pm_disc
    # - pm25grid_rad2_so4_pm_disc
      
    # - pm25grid_rad1_so4_pm_disc_sparse_10
    # - pm25grid_rad1_so4_pm_disc_sparse_30
      
    # - small_healthdgrid_rad1_pollutn_mortality_disc_singlecause_10
    # - small_healthdgrid_rad1_pollutn_mortality_disc_singlecause_30

algorithms:
  cont:
    # - spatial
    # - spatialplus
    # - xgboost
    # - ols
    # - gcn
    # - s2sls-lag1
    # - s2sls-lag2
    # - gmerror
    # - deconfounder
  disc:
    # - dapsm
    # - spatial
    # - spatialplus
    # - gcn
    # - s2sls-lag1
    # - unet
    
    # change r1 to "r0" or "r2" to change model radius
    # the last number in the name denotes the size of the latent dimension divided by 2
    # i.e. 64 --> d_z = 32
    
    # - deconfounder_r1_spatialplus_64
    # - deconfounder_r1_spatialplus_32
    # - deconfounder_r1_spatialplus_16
    # - deconfounder_r1_spatialplus_8
    - deconfounder_r1_spatialplus_4
    - deconfounder_r1_spatialplus_2
    
    # - deconfounder_r1_unet_64
    # - deconfounder_r1_unet_32
    # - deconfounder_r1_unet_16
    # - deconfounder_r1_unet_8
    # - deconfounder_r1_unet_4
    # - deconfounder_r1_unet_2

