needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  radius: 3
  connectivity: 8
  encoder_pool: max
  lr_cvae: 1e-3
  beta_epoch_max: 5
  epochs_cvae: 30
  encoder_conv1: 64
  encoder_conv2: 2
  # unet kwargs
  head: unet
  epochs_head: 30
  lr_head: 1e-3
  bilinear: false


tune:
  param_space:
    weight_decay_cvae:
      _target_: ray.tune.uniform
      _args_: [1e-4, 1e-3]
    weight_decay_head:
      _target_: ray.tune.uniform
      _args_: [1e-4, 1e-3]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-3, 1]
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]
