needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  connectivity: 8
  encoder_pool: max
  encoder_conv1: 64
  bilinear: true
  lr: 3e-4
  
  radius: 2
  latent_dim: 64
  encoder_conv2: 64
  weight_decay: 3e-5
  beta_max: 1e-8
  beta_epoch_max: 20
  gamma: 0.03
  epochs: 10
  unet_base_chan: 32


# tune:
#   param_space:
#     radius:
#       _target_: ray.tune.choice
#       _args_:
#         - [0, 1]
#     latent_dim:
#       _target_: ray.tune.choice
#       _args_: 
#         - [64, 128, 256, 512]
#     encoder_conv2:
#       _target_: ray.tune.choice
#       _args_: 
#         - [16, 32, 64, 128]
#     weight_decay:
#       _target_: ray.tune.loguniform
#       _args_: [3e-5, 1e-4]
#     beta_max:
#       _target_: ray.tune.loguniform
#       _args_: [1e-10, 1e-6]
#     beta_epoch_max:
#       _target_: ray.tune.choice
#       _args_:
#         - [20, 25, 30, 35]  
#     gamma:
#       _target_: ray.tune.uniform
#       _args_: [0.03, 0.1]
#     epochs:
#       _target_: ray.tune.choice
#       _args_:
#         - [200, 250, 300]  
#     unet_base_chan:
#       _target_: ray.tune.choice
#       _args_:
#         - [32, 64]
      