needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  radius: 2
  connectivity: 8
  encoder_pool: max
  lr_cvae: 1e-3
  beta_epoch_max: 5
  epochs_cvae: 50
  encoder_conv1: 64
  encoder_conv2: 8
  # spatialplus kwargs
  head: spatialplus
  max_iter: 2_500
  spatial_split_kwargs:
    init_frac: 0.02
    levels: 1
    # seed: 0
  k: 100


tune:
  param_space:
    weight_decay_cvae:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-3]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 10]
        
    lam_t:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1.0]
    lam_y:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1.0]
