needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  radius: 1
  connectivity: 8
  encoder_pool: max
  beta_epoch_max: 5
  epochs_cvae: 30
  encoder_conv1: 64
  # unet kwargs
  head: unet
  epochs_head: 30
  lr_head: 1e-3
  bilinear: false


tune:
  param_space:
    encoder_conv2:
      _target_: ray.tune.choice
      _args_:
        - [2, 4, 8, 16, 32, 64]
    lr_cvae:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-2]

    weight_decay_cvae:
      _target_: ray.tune.uniform
      _args_: [1e-7, 1e-3]
    weight_decay_head:
      _target_: ray.tune.uniform
      _args_: [1e-7, 1e-3]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-8, 1]
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]
