needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  radius: 1
  connectivity: 8
  encoder_pool: max
  bilinear: false
  lr: 3e-4
  beta_epoch_max: 10
  epochs: 30
  encoder_conv1: 64
  encoder_conv2: 8


tune:
  param_space:
    latent_dim:
      _target_: ray.tune.choice
      _args_: 
        - [8, 16, 32]
    weight_decay:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-2]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-2, 2e-1]
    gamma:
      _target_: ray.tune.loguniform
      _args_: [1e-3, 1e-1]
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]
      