needs_train_test_split: false
use_interference: true

method:
  _target_: sci.algorithms.Deconfounder
  kernel_size: 3
  radius: 0
  connectivity: 8
  encoder_pool: max
  bilinear: false
  lr_cvae: 3e-4
  lr_head: 1e-3
  beta_epoch_max: 10
  epochs_cvae: 30
  epochs_head: 30
  encoder_conv1: 64
  encoder_conv2: 8
  head: unet


tune:
  param_space:
    encoder_conv1:
      _target_: ray.tune.choice
      _args_: 
        - [4, 8, 16, 32, 64]
    encoder_conv2:
      _target_: ray.tune.choice
      _args_: 
        - [4, 8, 16, 32, 64]
    latent_dim:
      _target_: ray.tune.choice
      _args_: 
        - [4, 8, 16, 32]
    weight_decay_cvae:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1e-2]
    weight_decay_head:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1e-2]
    beta_max:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1]
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]