needs_train_test_split: false
use_interference: false

method:
  _target_: sci.algorithms.unet.TemporalU_Net
  base_channels: 32
  n_downs: 3
  bilinear: true
  weight_decay: 1e-4
  lr: 1e-3
  epochs: 50
  batch_size: 8


tune:
  param_space:
    base_channels:
      _target_: ray.tune.choice
      _args_:
        - [16, 32]
    lr:
      _target_: ray.tune.loguniform
      _args_: [1e-4, 1e-2]
    weight_decay:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1e-3]
    n_downs:
      _target_: ray.tune.choice
      _args_:
        - [2, 3]
