needs_train_test_split: false
use_interference: false

method:
  _target_: sci.algorithms.unet.U_Net
  lr: 1e-3
  epochs: 50
  bilinear: false


tune:
  param_space:
    unet_base_chan:
      _target_: ray.tune.choice
      _args_:
        - [8, 16, 32]
