upload_dataverse: sci
download_dataverse: sci
upload: false
token: ???
training_threads: 64
spaceenvs:  
  # nonlocal means NON LOCAL CONFOUNDING, otherwise there is local confounding
  
  # - small_healthdgrid_rad1_pollutn_mortality_disc
  # - small_healthdgrid_rad2_pollutn_mortality_disc
  
  # - pm25grid_rad1_so4_pm_disc
  # - pm25grid_rad2_so4_pm_disc
  
  # - nonlocal_pm25grid_rad1_so4_pm_disc
  - nonlocal_pm25grid_rad2_so4_pm_disc 
  
  # - nonlocal_small_healthdgrid_rad1_pollutn_mortality_disc
  # - nonlocal_small_healthdgrid_rad2_pollutn_mortality_disc
